---
- hosts: localhost
  gather_facts: yes
  become: yes
  tasks:
    - name: update Debian
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: update RedHat
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - ansible.builtin.package:
        name:
          - wrk
        state: present

- hosts: master
  tasks:
    - name: remove whoami service
      command: "docker service rm whoami"
      become: yes
      ignore_errors: True

    - name: create whoami service
      command: "docker service create --name whoami --publish published=8080,target=80 --replicas 1 containous/whoami"
      become: yes

    - name: update whoami service scale to 2
      command: "docker service update --replicas 2 whoami"
      become: yes

    - name: update whoami service scale to 4
      command: "docker service update --replicas 4 whoami"
      become: yes

    - name: update whoami service scale to 8
      command: "docker service update --replicas 8 whoami"
      become: yes



- hosts: localhost
  gather_facts: yes
  tasks:
    - name: wrk 1
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output

    - name:
      ansible.builtin.debug:
        msg: '{{ wrk_output.stdout_lines | select("search", "Req/Sec") }}'

    - name: wrk 2
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output2

    - name: debug wrk 2 output
      ansible.builtin.debug:
        msg: '{{ wrk_output2.stdout_lines | select("search", "Req/Sec") }}'

    - name: wrk 4
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output4

    - name: debug wrk 4 output
      ansible.builtin.debug:
        msg: '{{ wrk_output4.stdout_lines | select("search", "Req/Sec") }}'

    - name: wrk 8
      command: "wrk -t4 -c5 -d30s http://{{ hostvars | first }}:8080"
      register: wrk_output8

    - name: debug wrk 8 output
      ansible.builtin.debug:
        msg: '{{ wrk_output8.stdout_lines | select("search", "Req/Sec") }}'